### PR TITLE
Use angular package format (ng-packagr) for packaging

### PR DESCRIPTION
**Pull request by filipows**
Package the library to [angular package format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs)

https://github.com/ng-packagr/ng-packagr

Fixed for me #12

### CODE REVIEW

**Comment by khashayar** [comment]
Thanks for the PR. It's merged and new npm version (3.0.0) is released.

**Comment by filipows** [comment]
Hi @khashayar ,
thanks for a quick response. Unfortunately currently published version 3.0.0 doesn't work due to the wrong entry file.

It can be fixed by publishing only the `dist` folder:
`cd dist && npm publish`
or
`npm publish dist`

**Comment by khashayar** [comment]
Thanks for the heads-up! I tried to fix it by adding the `files` section into `package.json`. Can you please make sure if it's working now.

Thank you.

**Comment by filipows** [comment]
Thanks @khashayar , it works great now :slightly_smiling_face:

**Pull request merged**
